/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedLaporanRouteImport } from './routes/_authed/laporan'
import { Route as AuthedManajemenDataRouteImport } from './routes/_authed/manajemen-data'
import { Route as AuthedMurajaahRouteImport } from './routes/_authed/murajaah'
import { Route as AuthedPengaturanRouteImport } from './routes/_authed/pengaturan'
import { Route as AuthedZiyadahRouteImport } from './routes/_authed/ziyadah'
import { Route as ApiExportPdfRouteImport } from './routes/api/export-pdf'
import { Route as ApiExportPresensiRouteImport } from './routes/api/export-presensi'
import { Route as ApiParentAuthRouteImport } from './routes/api/parent-auth'
import { Route as ApiParentDataRouteImport } from './routes/api/parent-data'
import { Route as ApiPresensiRouteImport } from './routes/api/presensi'
import { Route as ApiSetoranRouteImport } from './routes/api/setoran'
import { Route as ApiSiswaRouteImport } from './routes/api/siswa'
import { Route as ApiSurahRouteImport } from './routes/api/surah'
import { Route as ApiUserProfileRouteImport } from './routes/api/user-profile'
import { Route as ApiWaliLinkRouteImport } from './routes/api/wali-link'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLaporanRoute = AuthedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedManajemenDataRoute = AuthedManajemenDataRouteImport.update({
  id: '/manajemen-data',
  path: '/manajemen-data',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMurajaahRoute = AuthedMurajaahRouteImport.update({
  id: '/murajaah',
  path: '/murajaah',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPengaturanRoute = AuthedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedZiyadahRoute = AuthedZiyadahRouteImport.update({
  id: '/ziyadah',
  path: '/ziyadah',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiExportPdfRoute = ApiExportPdfRouteImport.update({
  id: '/api/export-pdf',
  path: '/api/export-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportPresensiRoute = ApiExportPresensiRouteImport.update({
  id: '/api/export-presensi',
  path: '/api/export-presensi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParentAuthRoute = ApiParentAuthRouteImport.update({
  id: '/api/parent-auth',
  path: '/api/parent-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParentDataRoute = ApiParentDataRouteImport.update({
  id: '/api/parent-data',
  path: '/api/parent-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresensiRoute = ApiPresensiRouteImport.update({
  id: '/api/presensi',
  path: '/api/presensi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetoranRoute = ApiSetoranRouteImport.update({
  id: '/api/setoran',
  path: '/api/setoran',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiswaRoute = ApiSiswaRouteImport.update({
  id: '/api/siswa',
  path: '/api/siswa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSurahRoute = ApiSurahRouteImport.update({
  id: '/api/surah',
  path: '/api/surah',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserProfileRoute = ApiUserProfileRouteImport.update({
  id: '/api/user-profile',
  path: '/api/user-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaliLinkRoute = ApiWaliLinkRouteImport.update({
  id: '/api/wali-link',
  path: '/api/wali-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/laporan': typeof AuthedLaporanRoute
  '/manajemen-data': typeof AuthedManajemenDataRoute
  '/murajaah': typeof AuthedMurajaahRoute
  '/pengaturan': typeof AuthedPengaturanRoute
  '/ziyadah': typeof AuthedZiyadahRoute
  '/api/export-pdf': typeof ApiExportPdfRoute
  '/api/export-presensi': typeof ApiExportPresensiRoute
  '/api/parent-auth': typeof ApiParentAuthRoute
  '/api/parent-data': typeof ApiParentDataRoute
  '/api/presensi': typeof ApiPresensiRoute
  '/api/setoran': typeof ApiSetoranRoute
  '/api/siswa': typeof ApiSiswaRoute
  '/api/surah': typeof ApiSurahRoute
  '/api/user-profile': typeof ApiUserProfileRoute
  '/api/wali-link': typeof ApiWaliLinkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/laporan': typeof AuthedLaporanRoute
  '/manajemen-data': typeof AuthedManajemenDataRoute
  '/murajaah': typeof AuthedMurajaahRoute
  '/pengaturan': typeof AuthedPengaturanRoute
  '/ziyadah': typeof AuthedZiyadahRoute
  '/api/export-pdf': typeof ApiExportPdfRoute
  '/api/export-presensi': typeof ApiExportPresensiRoute
  '/api/parent-auth': typeof ApiParentAuthRoute
  '/api/parent-data': typeof ApiParentDataRoute
  '/api/presensi': typeof ApiPresensiRoute
  '/api/setoran': typeof ApiSetoranRoute
  '/api/siswa': typeof ApiSiswaRoute
  '/api/surah': typeof ApiSurahRoute
  '/api/user-profile': typeof ApiUserProfileRoute
  '/api/wali-link': typeof ApiWaliLinkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/register': typeof RegisterRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/laporan': typeof AuthedLaporanRoute
  '/_authed/manajemen-data': typeof AuthedManajemenDataRoute
  '/_authed/murajaah': typeof AuthedMurajaahRoute
  '/_authed/pengaturan': typeof AuthedPengaturanRoute
  '/_authed/ziyadah': typeof AuthedZiyadahRoute
  '/api/export-pdf': typeof ApiExportPdfRoute
  '/api/export-presensi': typeof ApiExportPresensiRoute
  '/api/parent-auth': typeof ApiParentAuthRoute
  '/api/parent-data': typeof ApiParentDataRoute
  '/api/presensi': typeof ApiPresensiRoute
  '/api/setoran': typeof ApiSetoranRoute
  '/api/siswa': typeof ApiSiswaRoute
  '/api/surah': typeof ApiSurahRoute
  '/api/user-profile': typeof ApiUserProfileRoute
  '/api/wali-link': typeof ApiWaliLinkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/parent'
    | '/register'
    | '/dashboard'
    | '/laporan'
    | '/manajemen-data'
    | '/murajaah'
    | '/pengaturan'
    | '/ziyadah'
    | '/api/export-pdf'
    | '/api/export-presensi'
    | '/api/parent-auth'
    | '/api/parent-data'
    | '/api/presensi'
    | '/api/setoran'
    | '/api/siswa'
    | '/api/surah'
    | '/api/user-profile'
    | '/api/wali-link'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/parent'
    | '/register'
    | '/dashboard'
    | '/laporan'
    | '/manajemen-data'
    | '/murajaah'
    | '/pengaturan'
    | '/ziyadah'
    | '/api/export-pdf'
    | '/api/export-presensi'
    | '/api/parent-auth'
    | '/api/parent-data'
    | '/api/presensi'
    | '/api/setoran'
    | '/api/siswa'
    | '/api/surah'
    | '/api/user-profile'
    | '/api/wali-link'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/parent'
    | '/register'
    | '/_authed/dashboard'
    | '/_authed/laporan'
    | '/_authed/manajemen-data'
    | '/_authed/murajaah'
    | '/_authed/pengaturan'
    | '/_authed/ziyadah'
    | '/api/export-pdf'
    | '/api/export-presensi'
    | '/api/parent-auth'
    | '/api/parent-data'
    | '/api/presensi'
    | '/api/setoran'
    | '/api/siswa'
    | '/api/surah'
    | '/api/user-profile'
    | '/api/wali-link'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRoute
  RegisterRoute: typeof RegisterRoute
  ApiExportPdfRoute: typeof ApiExportPdfRoute
  ApiExportPresensiRoute: typeof ApiExportPresensiRoute
  ApiParentAuthRoute: typeof ApiParentAuthRoute
  ApiParentDataRoute: typeof ApiParentDataRoute
  ApiPresensiRoute: typeof ApiPresensiRoute
  ApiSetoranRoute: typeof ApiSetoranRoute
  ApiSiswaRoute: typeof ApiSiswaRoute
  ApiSurahRoute: typeof ApiSurahRoute
  ApiUserProfileRoute: typeof ApiUserProfileRoute
  ApiWaliLinkRoute: typeof ApiWaliLinkRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/laporan': {
      id: '/_authed/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthedLaporanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/manajemen-data': {
      id: '/_authed/manajemen-data'
      path: '/manajemen-data'
      fullPath: '/manajemen-data'
      preLoaderRoute: typeof AuthedManajemenDataRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/murajaah': {
      id: '/_authed/murajaah'
      path: '/murajaah'
      fullPath: '/murajaah'
      preLoaderRoute: typeof AuthedMurajaahRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pengaturan': {
      id: '/_authed/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthedPengaturanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ziyadah': {
      id: '/_authed/ziyadah'
      path: '/ziyadah'
      fullPath: '/ziyadah'
      preLoaderRoute: typeof AuthedZiyadahRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/export-pdf': {
      id: '/api/export-pdf'
      path: '/api/export-pdf'
      fullPath: '/api/export-pdf'
      preLoaderRoute: typeof ApiExportPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-presensi': {
      id: '/api/export-presensi'
      path: '/api/export-presensi'
      fullPath: '/api/export-presensi'
      preLoaderRoute: typeof ApiExportPresensiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parent-auth': {
      id: '/api/parent-auth'
      path: '/api/parent-auth'
      fullPath: '/api/parent-auth'
      preLoaderRoute: typeof ApiParentAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parent-data': {
      id: '/api/parent-data'
      path: '/api/parent-data'
      fullPath: '/api/parent-data'
      preLoaderRoute: typeof ApiParentDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presensi': {
      id: '/api/presensi'
      path: '/api/presensi'
      fullPath: '/api/presensi'
      preLoaderRoute: typeof ApiPresensiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setoran': {
      id: '/api/setoran'
      path: '/api/setoran'
      fullPath: '/api/setoran'
      preLoaderRoute: typeof ApiSetoranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/siswa': {
      id: '/api/siswa'
      path: '/api/siswa'
      fullPath: '/api/siswa'
      preLoaderRoute: typeof ApiSiswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/surah': {
      id: '/api/surah'
      path: '/api/surah'
      fullPath: '/api/surah'
      preLoaderRoute: typeof ApiSurahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-profile': {
      id: '/api/user-profile'
      path: '/api/user-profile'
      fullPath: '/api/user-profile'
      preLoaderRoute: typeof ApiUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wali-link': {
      id: '/api/wali-link'
      path: '/api/wali-link'
      fullPath: '/api/wali-link'
      preLoaderRoute: typeof ApiWaliLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedLaporanRoute: typeof AuthedLaporanRoute
  AuthedManajemenDataRoute: typeof AuthedManajemenDataRoute
  AuthedMurajaahRoute: typeof AuthedMurajaahRoute
  AuthedPengaturanRoute: typeof AuthedPengaturanRoute
  AuthedZiyadahRoute: typeof AuthedZiyadahRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedLaporanRoute: AuthedLaporanRoute,
  AuthedManajemenDataRoute: AuthedManajemenDataRoute,
  AuthedMurajaahRoute: AuthedMurajaahRoute,
  AuthedPengaturanRoute: AuthedPengaturanRoute,
  AuthedZiyadahRoute: AuthedZiyadahRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRoute,
  RegisterRoute: RegisterRoute,
  ApiExportPdfRoute: ApiExportPdfRoute,
  ApiExportPresensiRoute: ApiExportPresensiRoute,
  ApiParentAuthRoute: ApiParentAuthRoute,
  ApiParentDataRoute: ApiParentDataRoute,
  ApiPresensiRoute: ApiPresensiRoute,
  ApiSetoranRoute: ApiSetoranRoute,
  ApiSiswaRoute: ApiSiswaRoute,
  ApiSurahRoute: ApiSurahRoute,
  ApiUserProfileRoute: ApiUserProfileRoute,
  ApiWaliLinkRoute: ApiWaliLinkRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
